First Commit To Creating font-awesome Addon
cybertoothca/ember-cli-font-awesome-sass pull request #1
Opened 2016-10-11 23:13 UTC by nadnoslen

2016-10-11 23:20 UTC, cherylcourt requested changes

2016-10-11 23:20 UTC, cherylcourt commented on blueprints/ember-cli-font-awesome-sass/index.js
> +  // }
Did you mean to leave this commented out code in this file?

2016-10-12 04:46 UTC, nadnoslen commented on README.md
> +## Installation
Added some installation documentation.

2016-10-12 04:46 UTC, nadnoslen commented on app/styles/_ember-cli-font-awesome-sass.scss
> +@import "../../bower_components/font-awesome/scss/font-awesome";
This file is the one that someone's app will import for compilation.  font-awesome will then be available.

2016-10-12 04:46 UTC, nadnoslen commented on blueprints/ember-cli-font-awesome-sass/index.js
> +    ]);
I need to see if this technique actually works.  Will npm link one of my apps.

2016-10-12 04:46 UTC, nadnoslen commented on index.js
> +      { destDir: "assets/font-awesome/fonts" });
I created issue #2 in order to consider improving destDir to be configured by an environment variable.

2016-10-12 04:48 UTC, cherylcourt commented on index.js
> +      { destDir: "assets/font-awesome/fonts" });
I saw that. 👍

2016-10-12 04:50 UTC, cherylcourt approved these changes
Neat.

2016-10-12 15:04 UTC, merged

2016-10-12 17:19 UTC, cherylcourt commented
Are you still working out of this branch or should it be deleted?